# GoReleaser configuration for goctx
# See https://goreleaser.com for detailed docs.

version: 2

project_name: goctx

env:
  - CGO_ENABLED=0

before:
  hooks:
    # Keep modules tidy before building artifacts
    - go mod tidy
    # Generate completions into a hidden cache folder.
    # This avoids the 'dist' cleanup and prevents parallel race conditions.
    - mkdir -p .buildcache/completions
    - sh -c "go run ./app/goctx completion bash > .buildcache/completions/goctx.bash"
    - sh -c "go run ./app/goctx completion zsh > .buildcache/completions/goctx.zsh"
    - sh -c "go run ./app/goctx completion fish > .buildcache/completions/goctx.fish"

builds:
  - id: goctx
    main: ./app/goctx
    binary: goctx
    flags:
      - -trimpath
    ldflags:
      - -s -w
      # Inject version metadata so the binary can print it without shelling out.
      - -X github.com/preminger/goctx/cmd/goctx/version.Version={{ .Version }}
      - -X github.com/preminger/goctx/cmd/goctx/version.Commit={{ .FullCommit }}
      - -X github.com/preminger/goctx/cmd/goctx/version.BuildDate={{ .Date }}
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - netbsd
      - openbsd
      - dragonfly
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - { goos: openbsd, goarch: arm, goarm: 6 }
      - { goos: windows, goarch: arm, goarm: 6 }

archives:
  - id: default
    ids: [goctx]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      # Map the completions from our cache into a 'completions' folder in the archive
      - src: .buildcache/completions/*
        dst: completions
        strip_parent: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-dev"

brews:
  - name: goctx
    repository:
      owner: preminger
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: Omer Preminger
      email: omer@preminger.xyz
    homepage: "https://github.com/preminger/goctx"
    description: "Make(file) replacement that is pure Go based (a fork of `makefile/mage`)."
    license: "Apache-2.0"

    # Installation logic for the binary and completions
    # We point to the 'completions' folder created in the archive step above
    install: |
      bin.install "goctx"
      bash_completion.install "completions/goctx.bash" => "goctx"
      zsh_completion.install "completions/goctx.zsh" => "_goctx"
      fish_completion.install "completions/goctx.fish"

    # Useful information displayed after 'brew install'
    caveats: |
      To enable completions, you may need to add the following to your shell profile, and then open a new shell:
        zsh:
          autoload -U compinit && compinit
        bash:
          [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"

    test: |
      system "#{bin}/goctx --version"

release:
  draft: false
  github:
    owner: preminger
    name: goctx
