# GoReleaser configuration for goctx
# See https://goreleaser.com for detailed docs.

version: 2

project_name: goctx

env:
  - CGO_ENABLED=0

before:
  hooks:
    # Keep modules tidy before building artifacts
    - go mod tidy

builds:
  - id: goctx
    main: ./app/goctx
    binary: goctx
    flags:
      - -trimpath
    ldflags:
      # Keep it minimal and safe; no package vars assumed.
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Optionally exclude unsupported combos here
    # ignore:
    #   - goos: darwin
    #     goarch: 386

archives:
  - id: default
    ids:
      - goctx
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'

release:
  # By default, GoReleaser infers GitHub/GitLab repo from the git remote.
  # This section can be extended if needed (e.g., to set draft, discussion category, etc.).
  draft: false
